services:
  pg_db:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_DB: "tasker"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123456"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - DATABASE_URL=postgres://admin:123456@db:5432/tasker?sslmode=disable
    depends_on:
      - pg_db